# Generated by Django 3.2.5 on 2022-04-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=8, null=True, verbose_name='연령대'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=2, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.IntegerField(default=0, verbose_name='ban여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_social_login',
            field=models.CharField(default='default', max_length=16, null=True, verbose_name='소셜로그인여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(error_messages={'unique': '이미 사용중인 핸드폰번호입니다.'}, max_length=16, null=True, unique=True, verbose_name='폰번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='성명'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=32, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
